project:
  type: website
  output-dir: docs
  
lang: en

execute:
  freeze: false
  cache: false
  
format:
  html:
    theme:
      light: minty
      dark: darkly
    callout-appearence: simple
    css: assets/all_css/styles.css
    toc: true
    toc-depth: 4
    smooth-scroll: true
    highlight-style: atom-one
    number-sections: true
    number-depth: 4

website:
  repo-url: https://github.com/UCLPG-MSC-SGDS/GEOG0186
  repo-actions: [issue]
  page-navigation: true
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 2
    logo: assets/all_images/sidebar_cosmetics/00_ucl_custom_geog0186_logo.png
    logo-href: https://www.ucl.ac.uk/module-catalogue/modules/foundations-of-geography-1-GEOG0186
    tools:
      - icon: github
        href: https://github.com/UCLPG-MSC-SGDS/GEOG0186
    contents:
      - section: "Module Overview"
        contents: 
          text: "Welcome"
          file: 00-module_overview.qmd
      - section: "Getting Started"
        contents:
          - 01-what_is_rstudio.qmd
      - section: "Core Content"
        contents:
          - 02-basic_building_blocks.qmd
          - 03-handling_data_structures.qmd
          - 04-frequency_distribution.qmd
          - 05-summary_measures.qmd
          - 06-data_visualisation.qmd
          - 07-sourcing_data_download.qmd
          - 08-probability_distribution.qmd
          - 09-london_airquality_relationships.qmd
          - 10-london_airquality_ttests.qmd